name: dart_alsa
description: Dart FFI Binding to the ALSA sound library
version: 0.0.3
homepage: https://github.com/maks/dart_alsa

# Supports only Linux
platforms:
  linux:

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  ffi: ^1.0.0
  tuple: ^2.0.0

dev_dependencies:
  ffigen: ^3.0.0
  pedantic: ^1.9.0

ffigen:
  name: "ALSA"
  output: "lib/alsa_generated_bindings.dart"
  headers:
    entry-points:
      - "/usr/include/alsa/asoundlib.h"
  compiler-opts: "-I/usr/lib/llvm-11/include/ -L/usr/lib/llvm-11/lib/
    -I/usr/local/opt/llvm/include/ -Wno-nullability-completeness"
  structs:
    rename:
      "_(.*)": "$1_"
    member-rename:
      ".*":
        "_(.*)": "$1_"
